### ISSUE TITLE
NEW VERSION CRASHES

### ISSUE THREAD

**Issue by toticorrea** [Dynious/RefinedRelocation#277]

**Comment by toticorrea** [comment]
I upgraded today to the new version. I couldn´t play bcouse game crashed. In the log, it said specifficly becouse one block extender. I closed the game, put it the old version, the f, and started over. I took out all the block extenders (5) and 1 wireless one and I saved and closed the game. Upograded agaion to the g version, started to play ok, but when I try to put the first block extender again, it crashed.

**Comment by toticorrea** [comment]
this was the last log:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 08/03/15 21:22
Description: Ticking block entity

java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyReceiver
	at com.dynious.refinedrelocation.tileentity.TileBlockExtender.checkConnectedDirection(TileBlockExtender.java:296)
	at com.dynious.refinedrelocation.tileentity.TileBlockExtender.func_145845_h(TileBlockExtender.java:229)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyReceiver
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.dynious.refinedrelocation.tileentity.TileBlockExtender.checkConnectedDirection(TileBlockExtender.java:296)
	at com.dynious.refinedrelocation.tileentity.TileBlockExtender.func_145845_h(TileBlockExtender.java:229)

-- Block entity being ticked --
Details:
	Name: blockExtender // com.dynious.refinedrelocation.tileentity.TileBlockExtender
	Block type: ID #1068 (tile.blockExtender // com.dynious.refinedrelocation.block.BlockExtender)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (37,56,331), Chunk: (at 5,3,11 in 2,20; contains blocks 32,0,320 to 47,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #1068 (tile.blockExtender // com.dynious.refinedrelocation.block.BlockExtender)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

**Comment by Dynious** [comment]
Danm, seems like I forgot to change the minimum needed CoFH Core version.

You'll need to update to the latest CoFH Core version and things should work.

**Comment by toticorrea** [comment]
working!
Thanks. I didn't have this CoFH before. Now I installed and everything is working so far.

**Comment by toticorrea** [comment]
A new one: Now with the g version and the last version of CoFH Core installed, my game crashes after 2-5 minutes playing, every time. No specific action. I'll post the log as soon as I open it again.

**Comment by toticorrea** [comment]
Regardless all the problems I comment in past issues I published, I could play fine so far with the "e" or "f" versions without the CoFH Core installed.

**Comment by Dynious** [comment]
When testing I couldn't get the same result, closing.
