### ISSUE TITLE
NPE crash when shift-right clicking a sorting iron chest after updating to latest version

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#301]
java.lang.NullPointerException: Ticking screen
	at net.minecraft.client.gui.inventory.GuiContainer.func_73876_c(GuiContainer.java:698)
	at com.dynious.refinedrelocation.client.gui.GuiRefinedRelocationContainer.func_73876_c(GuiRefinedRelocationContainer.java:114)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by blay09** [comment]
Wasn't reproduceable and the only thing that could be null in the function was mc or thePlayer, so blaming general Minecraft weirdness and closing this for now.
