### ISSUE TITLE
Wireless linker crash

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [Dynious/RefinedRelocation#370]
Hello,

I use forge recommended (1448) and when I use the wireless linker and the wireless block extender it crashes like this(on server):

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 24/10/15 17.36
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149694_d(Lnet/minecraft/world/World;III)Lnet/minecraft/item/Item;
        at net.minecraft.block.Block.getPickBlock(Block.java:1801)
        at com.dynious.refinedrelocation.helper.BlockHelper.getBlockDisplayName(BlockHelper.java:69)
        at com.dynious.refinedrelocation.helper.BlockHelper.getTileEntityDisplayName(BlockHelper.java:102)
        at com.dynious.refinedrelocation.item.ItemLinker.onItemUseFirst(ItemLinker.java:124)
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:48)
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

When I start the server and I enter I can see it's actually linked correctly, am I missing something.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you very much
