### ISSUE TITLE
NPE in PlayerBlockPlacement packet when checking filter in Relocator

### ISSUE THREAD

**Issue by Beiserkeren** [Dynious/RefinedRelocation#390]
When i try to check the filter in the Relocator i get this from server log

8:39:02  [Warn] Failed to handle packet for /XX:XX:XX:XX/java.lang.NullPointerException at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620) ~[nh.class:?]    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]   at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Beiserkeren** [comment]
btw iam not really sure what to send. This is what i get from server
