### ISSUE TITLE
Sorting Barrels do not rotate when placed with a dolly

### ISSUE THREAD

**Issue by finrod09** [Dynious/RefinedRelocation#63]
Picking up sorting barrels with a dolly causes an NPE (see below). When putting them down again, they do not reorient toward the player. The NPE does not cause a server crash - Occured on 1.6.4 1.0.1 and seems to occur every time.

```
2014-04-20 23:44:54 [INFO] [STDERR] java.lang.NullPointerException
2014-04-20 23:44:54 [INFO] [STDERR]     at com.dynious.refinedrelocation.block.BlockSortingBarrel.func_71852_a(BlockSortingBarrel.java:32)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.world.chunk.Chunk.func_76592_a(Chunk.java:711)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.world.World.func_72832_d(World.java:559)
2014-04-20 23:44:54 [INFO] [STDERR]     at mcp.mobius.betterbarrels.common.items.dolly.ItemBarrelMover.pickupContainer(ItemBarrelMover.java:426)
2014-04-20 23:44:54 [INFO] [STDERR]     at mcp.mobius.betterbarrels.common.items.dolly.ItemBarrelMover.onItemUseFirst(ItemBarrelMover.java:131)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:407)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:556)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-04-20 23:44:54 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

**Comment by kramarz** [comment]
This rotation bug is still present. Are JABBA developers willing to cooperate? Can you briefly explain root of problem? Maybe a workaround would be adding specialized tool to rotate RR barells.

**Comment by blay09** [comment]
The problem is that JABBA hardcodes everything and doesn't provide a usable API. There hasn't been a reaction to the issue posted on their issue tracker either. I've managed to work around Wooden Sorting Chests not being pickup-able by injecting ourself into JABBA's code, but rotation is something I can't fix on our side.

**Comment by kramarz** [comment]
I have wrote them a pull request. https://bitbucket.org/ProfMobius/jabba/pull-requests/34/add-api-for-dolly/diff 
They had already some classes which were unused anywhere in dolly.api package. 
Can you review it and tell me what is your opinion.

**Comment by codewarrior0** [comment]
Still a problem with RefinedRelocation-mc1.7.10-1.1.12 and Jabba-1.2.1a_1.7.10

**Comment by blay09** [comment]
And that's not gonna change unless JABBA stops hardcoding things and provides an API.

**Comment by kramarz** [comment]
Just look at my PR please (it is realy simple change - i just used foundation they already had). If we make them to merge it. Than I believe you would have your api. Another (ugly) option would be send them pull request with  hardcoded support as every other mod does.

I don't mod minecraft, so I want your opinion first before I start to ask them to merge it.
